CREATE TABLE IF NOT EXISTS USERS (
    id SERIAL PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    age INTEGER NOT NULL,
    numberOfRatedMedia INTEGER,
    gender VARCHAR(256) NOT NULL,
    version INTEGER
    );

CREATE TABLE IF NOT EXISTS Media (
    id SERIAL PRIMARY KEY,
    title VARCHAR(256) NOT NULL,
    releaseDate DATE NOT NULL,
    mediaType VARCHAR(256) NOT NULL,
    totalRating DOUBLE PRECISION NOT NULL,
    numberOfRates INTEGER NOT NULL,
    version INTEGER
    );

CREATE TABLE IF NOT EXISTS MediaRate (
    id SERIAL PRIMARY KEY,
    mediaId INTEGER NOT NULL REFERENCES Media(id) ON DELETE CASCADE,
    userId INTEGER NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
    rating DOUBLE PRECISION NOT NULL
    );