version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 123
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: 123
    networks:
      - server-network
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    networks:
      - server-network
    volumes:
      - ..:/workspace

networks:
  server-network:
